# More examples of Codefresh YAML can be found at
# https://codefresh.io/docs/docs/yaml-examples/examples/

version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "https://github.com/codefresh-io/cli/"
    # Clone the master branch. Or, use ${{CF_BRANCH}} to get branch name from trigger
    # Learn more at https://codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "master"
    stage: "clone"
hooks: 
  on_elected:
   steps:
     test:
       image: alpine
       commands: 
         - echo test<
